### ISSUE TITLE
Connection to irc.chat.twitch.tv:6697 failed during DNS lookup: Maximum function nesting level of '256' reached, aborting!

### ISSUE THREAD

**Issue by ghostzero** [ghostzero/tmi#3]
Due missing tmi credentials, we got this error:

```
Next RuntimeException: Connection to irc.chat.twitch.tv:6697 failed during DNS lookup: Maximum function nesting level of '256' reached, aborting! in /var/www/html/vendor/react/socket/src/DnsConnector.php:93
Stack trace:
#0 /var/www/html/vendor/react/promise/src/RejectedPromise.php(28): React\Socket\DnsConnector->React\Socket\{closure}(Object(Error))
#1 /var/www/html/vendor/react/socket/src/DnsConnector.php(94): React\Promise\RejectedPromise->then(Object(Closure), Object(Closure))
#2 /var/www/html/vendor/react/promise/src/Promise.php(245): React\Socket\DnsConnector->React\Socket\{closure}(Object(Closure), Object(Closure), Object(Closure))
#3 /var/www/html/vendor/react/promise/src/Promise.php(25): React\Promise\Promise->call(NULL)
#4 /var/www/html/vendor/react/socket/src/DnsConnector.php(112): React\Promise\Promise->__construct(NULL, NULL)
#5 /var/www/html/vendor/react/socket/src/SecureConnector.php(44): React\Socket\DnsConnector->connect('irc.chat.twitch...')
#6 /var/www/html/vendor/ghostzero/tmi/src/Client.php(162): React\Socket\SecureConnector->connect('irc.chat.twitch...')
#7 /var/www/html/vendor/ghostzero/tmi/src/Client.php(56): GhostZero\Tmi\Client->getConnectorPromise(Object(React\Socket\DnsConnector))
#8 /var/www/html/vendor/ghostzero/tmi/src/Client.php(180): GhostZero\Tmi\Client->connect()
#9 /var/www/html/vendor/react/event-loop/src/Timer/Timers.php(96): GhostZero\Tmi\Client->GhostZero\Tmi\{closure}(Object(React\EventLoop\Timer\Timer))
#10 /var/www/html/vendor/react/event-loop/src/StreamSelectLoop.php(184): React\EventLoop\Timer\Timers->tick()
#11 /var/www/html/vendor/ghostzero/tmi/src/Client.php(97): React\EventLoop\StreamSelectLoop->run()
#12 /var/www/html/vendor/ghostzero/tmi/src/Client.php(180): GhostZero\Tmi\Client->connect()
...
#221 /var/www/html/vendor/react/event-loop/src/Timer/Timers.php(96): GhostZero\Tmi\Client->GhostZero\Tmi\{closure}(Object(React\EventLoop\Timer\Timer))
#222 /var/www/html/vendor/react/event-loop/src/StreamSelectLoop.php(184): React\EventLoop\Timer\Timers->tick()
#223 /var/www/html/vendor/ghostzero/tmi/src/Client.php(97): React\EventLoop\StreamSelectLoop->run()
#224 /var/www/html/vendor/ghostzero/tmi-cluster/src/TmiClusterClient.php(124): GhostZero\Tmi\Client->connect()
#225 /var/www/html/vendor/ghostzero/tmi-cluster/src/Commands/TmiClusterProcessCommand.php(41): GhostZero\TmiCluster\TmiClusterClient->connect()
#226 [internal function]: GhostZero\TmiCluster\Commands\TmiClusterProcessCommand->handle()
#227 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): call_user_func_array(Array, Array)
#228 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#229 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(95): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#230 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(39): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#231 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(596): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#232 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\Container\Container->call(Array)
#233 /var/www/html/vendor/symfony/console/Command/Command.php(258): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#234 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#235 /var/www/html/vendor/symfony/console/Application.php(920): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#236 /var/www/html/vendor/symfony/console/Application.php(266): Symfony\Component\Console\Application->doRunCommand(Object(GhostZero\TmiCluster\Commands\TmiClusterProcessCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#237 /var/www/html/vendor/symfony/console/Application.php(142): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#238 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#239 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#240 /var/www/html/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#241 {main}
```

**Comment by ghostzero** [comment]
Reconnect loop is now fixed in v2.
